#!/bin/bash

GNUPLOT_OPTS="\
set boxwidth 0.95 relative; \
set style fill solid 0.5 noborder; \
set xlabel 'Revisions'; \
set ylabel 'Bytes used'; \
set xtics rotate by 45 offset -3,-2.2; \
set terminal png size 700,300 enhanced font 'Helvetica,10'; \
"
GNUPLOT_CMD_PRG="\
set output 'progmem.png'; \
set yrange [0:32*1024]; \
plot '-' using 2:xticlabel(4) with boxes title 'Program memory'; \
"
GNUPLOT_CMD_MEM="\
set output 'datamem.png'; \
set yrange [0:2*1024]; \
plot '-' using 3:xticlabel(4) with boxes title 'Data memory'; \
"

in="$(</dev/stdin)"
echo "$in" | gnuplot -e "$GNUPLOT_OPTS $GNUPLOT_CMD_PRG"
echo "$in" | gnuplot -e "$GNUPLOT_OPTS $GNUPLOT_CMD_MEM"
